# docker-compose.yml

version: '3.9'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    # Optionally, you can define networks or other services here
